# Generated by Django 5.1.13 on 2025-10-02 21:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('planta', models.IntegerField()),
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.habitaciones')),
            ],
        ),
    ]
